spring:
  application:
    name: proy-movimientos-service
  datasource:
    url: jdbc:mysql://localhost:3302/eurekabank
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root123
  freemarker:
    enabled: false
  thymeleaf:
    cache: false
    enabled: false
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
 
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka