spring:
  application:
    name: proy-categoria-service
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .html
  freemarker:
    enabled: false
  thymeleaf:
    enabled: false
    cache: false
    prefix: classpath:/templates/
  datasource:
    tienda:
      url: jdbc:mysql://localhost:3304/tienda
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root123

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka
      